[2025-09-19T15:05:11.672+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-19T15:05:11.706+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mayo_pipeline.etl_vitals manual__2025-09-19T15:05:10.678452+00:00 [queued]>
[2025-09-19T15:05:11.714+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mayo_pipeline.etl_vitals manual__2025-09-19T15:05:10.678452+00:00 [queued]>
[2025-09-19T15:05:11.715+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-19T15:05:11.729+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): etl_vitals> on 2025-09-19 15:05:10.678452+00:00
[2025-09-19T15:05:11.733+0000] {standard_task_runner.py:63} INFO - Started process 187 to run task
[2025-09-19T15:05:11.737+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'mayo_pipeline', 'etl_vitals', 'manual__2025-09-19T15:05:10.678452+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/mayo_pipeline.py', '--cfg-path', '/tmp/tmpbjlaxhz_']
[2025-09-19T15:05:11.741+0000] {standard_task_runner.py:91} INFO - Job 2: Subtask etl_vitals
[2025-09-19T15:05:11.816+0000] {task_command.py:426} INFO - Running <TaskInstance: mayo_pipeline.etl_vitals manual__2025-09-19T15:05:10.678452+00:00 [running]> on host aae1d613763d
[2025-09-19T15:05:12.116+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='you' AIRFLOW_CTX_DAG_ID='mayo_pipeline' AIRFLOW_CTX_TASK_ID='etl_vitals' AIRFLOW_CTX_EXECUTION_DATE='2025-09-19T15:05:10.678452+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-19T15:05:10.678452+00:00'
[2025-09-19T15:05:12.117+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-19T15:05:12.150+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-19T15:05:12.151+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "/bin/bash -lc 'set -euo pipefail; python /opt/project/etl/flatten_mimic_vitals.py'"]
[2025-09-19T15:05:12.160+0000] {subprocess.py:86} INFO - Output:
[2025-09-19T15:05:13.872+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-09-19T15:05:13.873+0000] {subprocess.py:93} INFO -   File "/opt/project/etl/flatten_mimic_vitals.py", line 69, in <module>
[2025-09-19T15:05:13.875+0000] {subprocess.py:93} INFO -     main()
[2025-09-19T15:05:13.875+0000] {subprocess.py:93} INFO -   File "/opt/project/etl/flatten_mimic_vitals.py", line 21, in main
[2025-09-19T15:05:13.877+0000] {subprocess.py:93} INFO -     df = pd.read_csv(SRC, nrows=NROWS)
[2025-09-19T15:05:13.878+0000] {subprocess.py:93} INFO -          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-09-19T15:05:13.878+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
[2025-09-19T15:05:13.879+0000] {subprocess.py:93} INFO -     return _read(filepath_or_buffer, kwds)
[2025-09-19T15:05:13.879+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-09-19T15:05:13.879+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 611, in _read
[2025-09-19T15:05:13.880+0000] {subprocess.py:93} INFO -     parser = TextFileReader(filepath_or_buffer, **kwds)
[2025-09-19T15:05:13.880+0000] {subprocess.py:93} INFO -              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-09-19T15:05:13.880+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
[2025-09-19T15:05:13.880+0000] {subprocess.py:93} INFO -     self._engine = self._make_engine(f, self.engine)
[2025-09-19T15:05:13.881+0000] {subprocess.py:93} INFO -                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-09-19T15:05:13.881+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
[2025-09-19T15:05:13.881+0000] {subprocess.py:93} INFO -     self.handles = get_handle(
[2025-09-19T15:05:13.882+0000] {subprocess.py:93} INFO -                    ^^^^^^^^^^^
[2025-09-19T15:05:13.882+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/pandas/io/common.py", line 755, in get_handle
[2025-09-19T15:05:13.882+0000] {subprocess.py:93} INFO -     handle = gzip.GzipFile(  # type: ignore[assignment]
[2025-09-19T15:05:13.883+0000] {subprocess.py:93} INFO -              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-09-19T15:05:13.883+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.11/gzip.py", line 174, in __init__
[2025-09-19T15:05:13.883+0000] {subprocess.py:93} INFO -     fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
[2025-09-19T15:05:13.884+0000] {subprocess.py:93} INFO -                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-09-19T15:05:13.884+0000] {subprocess.py:93} INFO - FileNotFoundError: [Errno 2] No such file or directory: 'data/physionet.org/files/mimic-iv-ed-demo/2.2/ed/vitalsign.csv.gz'
[2025-09-19T15:05:13.980+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-09-19T15:05:13.982+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-19T15:05:13.991+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-09-19T15:05:13.995+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=mayo_pipeline, task_id=etl_vitals, run_id=manual__2025-09-19T15:05:10.678452+00:00, execution_date=20250919T150510, start_date=20250919T150511, end_date=20250919T150513
[2025-09-19T15:05:14.014+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 2 for task etl_vitals (Bash command failed. The command returned a non-zero exit code 1.; 187)
[2025-09-19T15:05:14.038+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-09-19T15:05:14.059+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-19T15:05:14.063+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
